In [2]:
import numpy as np

In [8]:
np?

Type:        module
String form: <module 'numpy' from 'C:\\Python39\\lib\\site-packages\\numpy\\__init__.py'>
File:        c:\python39\lib\site-packages\numpy\__init__.py
Docstring:  
NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://www.scipy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as `np`::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-

In [9]:
np.__version__

'1.21.2'

In [10]:
npList = np.array([100,200,300,400,500])

In [11]:
type(npList)

numpy.ndarray

In [18]:
npList2 = npList*5

In [19]:
npList2

array([ 500, 1000, 1500, 2000, 2500])

In [14]:
npList2[3]

333600

In [15]:
npList3 = np.array([1,'abc',True])

In [16]:
npList3

array(['1', 'abc', 'True'], dtype='<U11')

In [20]:
npList + npList2

array([ 600, 1200, 1800, 2400, 3000])

In [22]:
npList2+25

array([ 525, 1025, 1525, 2025, 2525])

In [23]:
npTup = np.array((100,200,300))

In [24]:
npTup*2

array([200, 400, 600])

In [41]:
npND = np.array([[1,2,3],[4,5,6],[7,8,9]], ndmin=3)

In [42]:
npND

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [43]:
npND.ndim

3

In [48]:
npND[0,1,2]

6

In [14]:
arr1 = np.array([1,2],[3,4])
arr2 = np.array([5,6],[7,8])

arr = np.dstack((arr1,arr2))

arr

TypeError: Field elements must be 2- or 3-tuples, got '3'

In [4]:
arrsp = np.array([1,2,3,4,5,6,7,8,9])

arrSp = np.array_split(arrsp, 3,)
arrSp

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [8]:
arrSearch = np.array([1,2,3,4,5,6,7,8,9])

num = np.where(arrSearch == 4)
num

(array([3], dtype=int64),)