In [4]:
import numpy as np

def mtrAdd(mtrA,mtrB):
    return mtrA + mtrB

mtrA = np.array([[1,2,3,4],[5,6,7,8],[2,4,6,8],[1,3,5,7]])
mtrB = np.array([[1,2,3,4],[5,6,7,8],[2,4,6,8],[1,3,5,7]])

print(mtrAdd(mtrA, mtrB))

[[ 2  4  6  8]
 [10 12 14 16]
 [ 4  8 12 16]
 [ 2  6 10 14]]
