# <center> Shri Ramdeobaba College of Engineering and Management, Nagpur</center>
## <center>Department of Computer Science Engineering</center>
## <center>Python Programming LAB (CAP 204) (2021-2022)</center>
## <center>Practical - 05</center>

---

#### <strong>Name : </strong> <em>Shantanu Mane</em>
#### <strong>Roll Number : </strong> <em>63 (E-4)</em>
#### <strong>Section : </strong> <em>E (AIML)</em>
#### <strong>Date : </strong> <em>20<sup>th</sup> January 2022</em>

In [6]:
# Solution 1.

import numpy as np

def mtrAdd(mtrA,mtrB):
    return mtrA + mtrB

def mtrSub(mtrA,mtrB):
    return mtrA - mtrB

def mtrMul(mtrA,mtrB):
    return np.dot(mtrA,mtrB)

mtrA = np.array([[1,2,3,4],[5,6,7,8],[2,4,6,8],[1,3,5,7]])
mtrB = np.array([[3,1,4,5],[6,1,7,8],[8,3,1,6],[2,6,3,8]])

print("Addition of two matrices : \n",mtrAdd(mtrA, mtrB))
print("\nSubtraction of two matrices : \n",mtrSub(mtrA, mtrB))
print("\nMultiplication of two matrices : \n",mtrMul(mtrA, mtrB))

Addition of two matrices : 
 [[ 4  3  7  9]
 [11  7 14 16]
 [10  7  7 14]
 [ 3  9  8 15]]

Subtraction of two matrices : 
 [[-2  1 -1 -1]
 [-1  5  0  0]
 [-6  1  5  2]
 [-1 -3  2 -1]]

Multiplication of two matrices : 
 [[ 47  36  33  71]
 [123  80  93 179]
 [ 94  72  66 142]
 [ 75  61  51 115]]


In [5]:
# Solution 2.

CustomArray = np.arange(100,200,10)
CustomArray = CustomArray.reshape(5,2)
print("5 x 2 array with data between 100 and 200 with step value of 10 : \n", CustomArray)

5 x 2 array with data between 100 and 200 with step value of 10 : 
 [[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [12]:
# Solution 3.

M1=([[2,3,4], [6,5,2], [6,7,3]])
M2=([[1,4,2], [4,3,6],[5,9,8]])

print("Dot product of matrices : \n", np.dot(M1, M2))
print("\nInner product of matrices : \n", np.inner(M1, M2))
print("\nCross product of matrices : \n", np.cross(M1, M2))
print("\nOuter product of matrices : \n", np.outer(M1, M2))

Dot product of matrices : 
 [[34 53 54]
 [36 57 58]
 [49 72 78]]

Inner product of matrices : 
 [[ 22  41  69]
 [ 30  51  91]
 [ 40  63 117]]

Cross product of matrices : 
 [[-10   0   5]
 [ 24 -28  -2]
 [ 29 -33  19]]

Outer product of matrices : 
 [[ 2  8  4  8  6 12 10 18 16]
 [ 3 12  6 12  9 18 15 27 24]
 [ 4 16  8 16 12 24 20 36 32]
 [ 6 24 12 24 18 36 30 54 48]
 [ 5 20 10 20 15 30 25 45 40]
 [ 2  8  4  8  6 12 10 18 16]
 [ 6 24 12 24 18 36 30 54 48]
 [ 7 28 14 28 21 42 35 63 56]
 [ 3 12  6 12  9 18 15 27 24]]


In [22]:
# Solution 4.

markList = np.random.randint(40,76,dtype=int,size=80)

percentile = np.percentile(markList, 70)

print("Marks of students : \n", markList, "\n70 percentile of marks : ", percentile)

Marks of students : 
 [50 58 57 44 74 50 68 65 64 48 50 53 71 64 67 45 43 73 49 70 51 74 58 58
 40 67 57 51 71 41 42 61 50 45 42 56 75 47 54 69 44 71 61 44 70 44 61 74
 68 58 43 67 52 70 48 54 60 58 51 52 43 59 67 42 51 73 71 62 48 52 75 74
 75 42 44 70 70 59 63 48] 
70 percentile of marks :  67.0


In [27]:
# Solution 5.

from numpy import linalg

Arr = ([[1,4,8], [8,9,2],[9,7,8]])

eigenVal, eigenVect = np.linalg.eig(Arr)

print("Eigen Values : \n", eigenVal, "\nEigen Vector : \n", eigenVect)

Eigen Values : 
 [18.61713304 -4.50451282  3.88737977] 
Eigen Vector : 
 [[-0.44798294 -0.82768979  0.36471887]
 [-0.52339057  0.43844259 -0.77347804]
 [-0.7248266   0.35028233  0.51837426]]
