In [1]:
import numpy as np

In [3]:
firstArr = np.array([1,2,3]) # 1-dimensional Array
firstArr

array([1, 2, 3])

In [4]:
secondArr = np.array([[1,2,3],[4,5,6]]) # 2-dimensional Array
secondArr

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.ndim(firstArr)

1

In [8]:
np.ndim(secondArr)

2

In [10]:
Arr = np.arange(10)
Arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
Arr.dtype

dtype('int32')

In [14]:
firstArr.shape

(3,)

In [15]:
secondArr.shape

(2, 3)

In [18]:
thirdArr = np.array([[[1,2,3],[4,5,6],[7,8,9]]]) # 3-dimensional Array
thirdArr

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [25]:
Arr2 = np.arange(10)
Arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arrSq = np.array([[1,2],[3,4]])
arrSq

array([[1, 2],
       [3, 4]])

In [30]:
print(arrSq[0,0], arrSq[0,1],arrSq[1,0],arrSq[1,1])

1 2 3 4


In [54]:
idenMtx = np.eye(3,dtype='int64')
idenMtx.dtype

np.savetxt('idenMtx.txt', idenMtx)

In [50]:
arrSl = np.arange(20,dtype='int64')
arrSl

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19], dtype=int64)

In [51]:
arrSl[:10:3]

array([0, 3, 6, 9], dtype=int64)

In [74]:
arrCo = np.arange(10)
copyArr = arrCo.copy()

copyArr[3] = 239
print(arrCo,"\n",copyArr,"\n",copyArr.base)

[0 1 2 3 4 5 6 7 8 9] 
 [  0   1   2 239   4   5   6   7   8   9] 
 None


In [75]:
ArrVi = np.arange(10)
viewArr = ArrVi.view()

viewArr[3] = 813
print(ArrVi,"\n",viewArr,"\n",viewArr.base)

[  0   1   2 813   4   5   6   7   8   9] 
 [  0   1   2 813   4   5   6   7   8   9] 
 [  0   1   2 813   4   5   6   7   8   9]


In [76]:
np.matmul(viewArr,copyArr)

194583